// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewCjWQHiDHTLftvKB1hcv5mgrxHlmsDI',
    appId: '1:249363615823:web:74bd6ad45a47fd991eda3a',
    messagingSenderId: '249363615823',
    projectId: 'yojana-cd5f2',
    authDomain: 'yojana-cd5f2.firebaseapp.com',
    storageBucket: 'yojana-cd5f2.firebasestorage.app',
    measurementId: 'G-DRQH9JDJP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDslEWxQ7pw_cf75S3oOtcT3Uxg7llHwY8',
    appId: '1:249363615823:android:c8853909350403511eda3a',
    messagingSenderId: '249363615823',
    projectId: 'yojana-cd5f2',
    storageBucket: 'yojana-cd5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNZLb3KysLoHaUAVKUo7BW09MEIw1z6Qc',
    appId: '1:249363615823:ios:70dffb9a17addb9a1eda3a',
    messagingSenderId: '249363615823',
    projectId: 'yojana-cd5f2',
    storageBucket: 'yojana-cd5f2.firebasestorage.app',
    iosClientId:
        '249363615823-5u443nctc8bomttj2e6duj804ie74rue.apps.googleusercontent.com',
    iosBundleId: 'com.example.yojana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNZLb3KysLoHaUAVKUo7BW09MEIw1z6Qc',
    appId: '1:249363615823:ios:70dffb9a17addb9a1eda3a',
    messagingSenderId: '249363615823',
    projectId: 'yojana-cd5f2',
    storageBucket: 'yojana-cd5f2.firebasestorage.app',
    iosClientId:
        '249363615823-5u443nctc8bomttj2e6duj804ie74rue.apps.googleusercontent.com',
    iosBundleId: 'com.example.yojana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDewCjWQHiDHTLftvKB1hcv5mgrxHlmsDI',
    appId: '1:249363615823:web:b84ad2c1854a5a591eda3a',
    messagingSenderId: '249363615823',
    projectId: 'yojana-cd5f2',
    authDomain: 'yojana-cd5f2.firebaseapp.com',
    storageBucket: 'yojana-cd5f2.firebasestorage.app',
    measurementId: 'G-C3HLZSTRZ2',
  );
}
